apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sa-platform-runtime
  namespace: sa-p8-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: sa-platform-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sa-p8/prod/runtime
