apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: sa-p9-202203069
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: sa-p9
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: platform-datastores, namespace: sa-p9-prod}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: gcp-secret-manager}
  target: {name: platform-datastores, creationPolicy: Owner}
  dataFrom: [{extract: {key: platform-datastores}}]
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: auth-runtime, namespace: sa-p9-prod}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: gcp-secret-manager}
  target: {name: auth-runtime, creationPolicy: Owner}
  dataFrom: [{extract: {key: auth-runtime}}]
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: products-runtime, namespace: sa-p9-prod}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: gcp-secret-manager}
  target: {name: products-runtime, creationPolicy: Owner}
  dataFrom: [{extract: {key: products-runtime}}]
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: orders-runtime, namespace: sa-p9-prod}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: gcp-secret-manager}
  target: {name: orders-runtime, creationPolicy: Owner}
  dataFrom: [{extract: {key: orders-runtime}}]
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: notifications-runtime, namespace: sa-p9-prod}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: gcp-secret-manager}
  target: {name: notifications-runtime, creationPolicy: Owner}
  dataFrom: [{extract: {key: notifications-runtime}}]
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: cron-runtime, namespace: sa-p9-prod}
spec:
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: gcp-secret-manager}
  target: {name: cron-runtime, creationPolicy: Owner}
  dataFrom: [{extract: {key: cron-runtime}}]
