replicaCount: 3
image:
  tag: "0.9.0"
env:
  LOG_LEVEL: warn
ingress:
  enabled: true
  host: p8.example.com
resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 750m
    memory: 512Mi
