replicaCount: 2

image:
  repository: ghcr.io/carbonell-castillo/orders-service
  tag: "1.0.0"

service:
  port: 4003
  targetPort: 4003

health:
  path: /api/health

env:
  LOG_LEVEL: info
  PORT: "4003"
  PRODUCTS_SERVICE_URL: http://products-service-stable:4002/graphql

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
