apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sa-platform
  namespace: argocd
spec:
  description: Practica 9 - plataforma GitOps recuperable
  sourceRepos:
    - https://github.com/Carbonell-Castillo/Practicas-SA-B-202203069-gitops.git
  destinations:
    - namespace: sa-p9-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: kyverno.io
      kind: ClusterPolicy
    - group: external-secrets.io
      kind: ClusterSecretStore
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
