apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Prohibir latest
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-non-latest-tag
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [sa-p8-prod]
      validate:
        message: Las imágenes no pueden utilizar la etiqueta latest.
        pattern:
          spec:
            containers:
              - image: "!*:latest"
